package edu.empleado.mx.view;

import edu.empleado.mx.bo.EmpleadoBO;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan Esquivel Flores
 */
public class FrmUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmpleados
     */
    
    private EmpleadoBO ebo = new EmpleadoBO();
    
    public FrmUsuarios() {
        initComponents();
    }

    public void listarEmpleado()
    {
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNoEmp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPriAp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSecAp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPswd = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JComboBox<>();
        txtEstatus = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        txtTel1 = new javax.swing.JTextField();
        txtTel2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Numero de Empleado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        txtNoEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtNoEmp.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtNoEmp.setForeground(new java.awt.Color(0, 0, 0));
        txtNoEmp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNoEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 220, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Altas usuarios");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre(s): ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        txtPriAp.setBackground(new java.awt.Color(255, 255, 255));
        txtPriAp.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtPriAp.setForeground(new java.awt.Color(0, 0, 0));
        txtPriAp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPriApActionPerformed(evt);
            }
        });
        jPanel1.add(txtPriAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 250, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Primer apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txtSecAp.setBackground(new java.awt.Color(255, 255, 255));
        txtSecAp.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtSecAp.setForeground(new java.awt.Color(153, 153, 153));
        txtSecAp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSecApActionPerformed(evt);
            }
        });
        jPanel1.add(txtSecAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 250, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Segundo apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 260, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Correo principal:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Correo secundario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        txtTel.setBackground(new java.awt.Color(255, 255, 255));
        txtTel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtTel.setForeground(new java.awt.Color(0, 0, 0));
        txtTel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtTelActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 250, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        txtNom.setBackground(new java.awt.Color(255, 255, 255));
        txtNom.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtNom.setForeground(new java.awt.Color(0, 0, 0));
        txtNom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNomActionPerformed(evt);
            }
        });
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 250, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Departamento:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        txtPswd.setBackground(new java.awt.Color(255, 255, 255));
        txtPswd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtPswd.setForeground(new java.awt.Color(0, 0, 0));
        txtPswd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPswdActionPerformed(evt);
            }
        });
        jPanel1.add(txtPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 260, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Sexo:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        txtGenero.setBackground(new java.awt.Color(255, 255, 255));
        txtGenero.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtGenero.setForeground(new java.awt.Color(0, 0, 0));
        txtGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elije una opción", "H", "M", "O" }));
        txtGenero.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        txtEstatus.setBackground(new java.awt.Color(255, 255, 255));
        txtEstatus.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtEstatus.setForeground(new java.awt.Color(0, 0, 0));
        txtEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elije una opción", "ACTIVO", "BAJA" }));
        txtEstatus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEstatusActionPerformed(evt);
            }
        });
        jPanel1.add(txtEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 150, -1));

        btnAgregar.setBackground(new java.awt.Color(153, 153, 153));
        btnAgregar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        btnSalir.setBackground(new java.awt.Color(153, 153, 153));
        btnSalir.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Siguiente");
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        btnClean.setBackground(new java.awt.Color(153, 153, 153));
        btnClean.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnClean.setForeground(new java.awt.Color(0, 0, 0));
        btnClean.setText("Limpiar");
        btnClean.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCleanActionPerformed(evt);
            }
        });
        jPanel1.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("RFC:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CURP:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        btnSalir1.setBackground(new java.awt.Color(153, 153, 153));
        btnSalir1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        txtTel1.setBackground(new java.awt.Color(255, 255, 255));
        txtTel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtTel1.setForeground(new java.awt.Color(0, 0, 0));
        txtTel1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtTel1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 260, -1));

        txtTel2.setBackground(new java.awt.Color(255, 255, 255));
        txtTel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtTel2.setForeground(new java.awt.Color(0, 0, 0));
        txtTel2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtTel2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoEmpActionPerformed

    private void txtPriApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriApActionPerformed

    private void txtSecApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecApActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstatusActionPerformed

    private void txtPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswdActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (txtNoEmp.getText().isEmpty()) JOptionPane.showMessageDialog(null,"Llene todos los campos.");
        else if (txtNom.getText().isEmpty()) JOptionPane.showMessageDialog(null,"Llene todos los campos.");
        else if (txtPriAp.getText().isEmpty()) JOptionPane.showMessageDialog(null,"Llene todos los campos.");
        else if (txtSecAp.getText().isEmpty()) JOptionPane.showMessageDialog(null,"Llene todos los campos.");
        else if (txtEmail.getText().isEmpty()) JOptionPane.showMessageDialog(null,"Llene todos los campos.");
        else if (txtPswd.getText().isEmpty()) JOptionPane.showMessageDialog(null,"Llene todos los campos.");
        else if (txtTel.getText().isEmpty()) JOptionPane.showMessageDialog(null,"Llene todos los campos.");
        else if (txtGenero.getSelectedItem() == null) JOptionPane.showMessageDialog(null,"Llene todos los campos.");
        else if (txtEstatus.getSelectedItem() == null) JOptionPane.showMessageDialog(null,"Llene todos los campos.");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtNoEmp.setText("");
        txtNom.setText("");
        txtPriAp.setText("");
        txtSecAp.setText("");
        txtEmail.setText("");
        txtPswd.setText("");
        txtTel.setText("");
        txtGenero.removeAllItems();
        txtEstatus.removeAllItems();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalir1ActionPerformed
    {//GEN-HEADEREND:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void txtTel1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtTel1ActionPerformed
    {//GEN-HEADEREND:event_txtTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTel1ActionPerformed

    private void txtTel2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtTel2ActionPerformed
    {//GEN-HEADEREND:event_txtTel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTel2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtEstatus;
    private javax.swing.JComboBox<String> txtGenero;
    private javax.swing.JTextField txtNoEmp;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPriAp;
    private javax.swing.JPasswordField txtPswd;
    private javax.swing.JTextField txtSecAp;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTel1;
    private javax.swing.JTextField txtTel2;
    // End of variables declaration//GEN-END:variables
}
